name: Main AMI Build
on:
  push:
    branches: [ 'main' ]

jobs:
  ami:
    name: Build AMI
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-to-assume: ContinuousDelivery
          role-external-id: ${{ secrets.EXTERNAL_ID }}
          role-duration-seconds: 900
      - name: Create bin directory
        run: |
          mkdir -p $HOME/.local/bin
      - name: Install jkcfg
        run: |
          curl -L https://github.com/jkcfg/jk/releases/download/0.4.0/jk-linux-amd64 -o $HOME/.local/bin/jk
          chmod +x $HOME/.local/bin/jk
      - name: Install Packer
        run: |
          curl https://releases.hashicorp.com/packer/1.6.5/packer_1.6.5_linux_amd64.zip -o /tmp/packer_1.6.5_linux_amd64.zip
          unzip -d $HOME/.local/bin/ /tmp/packer_1.6.5_linux_amd64.zip
      - name: Install Packer Post Processor Plugin
        run: |
          curl -L https://github.com/wata727/packer-post-processor-amazon-ami-management/releases/download/v0.9.0/packer-post-processor-amazon-ami-management_0.9.0_linux_amd64.zip -o /tmp/packer-post-processor-amazon-ami-management_0.9.0_linux_amd64.zip
          unzip -j -d $HOME/.local/bin/ /tmp/packer-post-processor-amazon-ami-management_0.9.0_linux_amd64.zip
      - name: Update PATH
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Generate Packer config
        run: |
          make dist
      - name: Build AMI
        run: |
          make build
        




